// SPDX-License-Identifier: (Apache-2.0 OR MIT)
// Generated by M365 Copilot on 2025-12-17
// Refactor: Split DCAT3 exporter into base + format-specific subclasses.
package io.gdcc.spi.export.dcat3;

import static io.gdcc.spi.export.dcat3.config.loader.FileResolver.resolveElementFile;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.gdcc.spi.export.ExportDataProvider;
import io.gdcc.spi.export.ExportException;
import io.gdcc.spi.export.Exporter;
import io.gdcc.spi.export.dcat3.config.loader.ResourceConfigLoader;
import io.gdcc.spi.export.dcat3.config.loader.RootConfigLoader;
import io.gdcc.spi.export.dcat3.config.model.Element;
import io.gdcc.spi.export.dcat3.config.model.Relation;
import io.gdcc.spi.export.dcat3.config.model.ResourceConfig;
import io.gdcc.spi.export.dcat3.config.model.RootConfig;
import io.gdcc.spi.export.dcat3.config.validate.Severity;
import io.gdcc.spi.export.dcat3.config.validate.ValidationMessage;
import io.gdcc.spi.export.dcat3.config.validate.ValidationReport;
import io.gdcc.spi.export.dcat3.config.validate.Validators;
import io.gdcc.spi.export.dcat3.mapping.JaywayJsonFinder;
import io.gdcc.spi.export.dcat3.mapping.Prefixes;
import io.gdcc.spi.export.dcat3.mapping.ResourceMapper;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.ResIterator;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.shared.JenaException;
import org.apache.jena.vocabulary.RDF;

/**
 * Abstract base class for DCAT3 exporters.
 *
 * Each concrete subclass decides its own media type and serialization format.
 */
public abstract class Dcat3ExporterBase implements Exporter {

    private static final Logger logger = Logger.getLogger(Dcat3ExporterBase.class.getCanonicalName());

    protected RootConfig root;

    protected Dcat3ExporterBase() {
        try {
            this.root = RootConfigLoader.load();
        } catch (IOException e) {
            logger.warning("cannot read configuration: " + e.getMessage());
        }
    }

    public Boolean isHarvestable() {
        return root.formats().containsKey(getConfigurationKey())
                ? root.formats().get(getConfigurationKey()).harvestable()
                : false;
    }

    public Boolean isAvailableToUsers() {
        return root.formats().containsKey(getConfigurationKey())
                ? root.formats().get(getConfigurationKey()).availableToUsers()
                : false;
    }

    /** The MIME type advertised by this exporter. */
    protected abstract String getMediaTypeValue();

    /** The Jena writer name (e.g. "TURTLE", "JSON-LD", "RDF/XML"). */
    protected abstract String getJenaWriterName();

    /** The key in the configuration */
    protected abstract String getConfigurationKey();

    /** The display name shown when no override is configured in dcat-root.properties. */
    protected abstract String getDefaultDisplayName();

    @Override
    public String getDisplayName(Locale locale) {
        if (root != null && root.formats().containsKey(getConfigurationKey())) {
            String configured = root.formats().get(getConfigurationKey()).displayName();
            if (configured != null && !configured.isEmpty()) {
                return configured;
            }
        }
        return getDefaultDisplayName();
    }

    @Override
    public String getMediaType() {
        return getMediaTypeValue();
    }

    @Override
    public void exportDataset(ExportDataProvider dataProvider, OutputStream outputStream) throws ExportException {
        try {
            validateRootOrThrow(root);

            ExportData exportData = buildExportData(dataProvider);
            ObjectMapper mapper = new ObjectMapper();

            traceInputIfEnabled(mapper, exportData, root);

            JsonNode rootJson = mapper.valueToTree(exportData);
            JaywayJsonFinder finder = new JaywayJsonFinder(rootJson);
            Prefixes prefixes = new Prefixes(root.prefixes());

            MapBuildResult build = buildElementModels(root, finder, prefixes);

            validateAllOrThrow(root, build.elementConfigs());

            Model merged = mergeModels(prefixes, build.models());
            applyRelations(merged, prefixes, root.relations(), build.subjects());

            writeAtomic(merged, getJenaWriterName(), outputStream);

        } catch (JenaException | IOException e) {
            logger.warning(e.getMessage());
            throw new ExportException("DCAT export failed", e);
        }
    }

    // ---------------------------------------------------------------------------
    // Orchestration helpers (3.1 refactor)
    // ---------------------------------------------------------------------------

    private static void validateRootOrThrow(RootConfig root) throws ExportException {
        ValidationReport rootReport = Validators.validateRoot(root);
        for (ValidationMessage message : rootReport.messages()) {
            logger.log(message.severity() == Severity.ERROR ? Level.SEVERE : Level.WARNING, message.toString());
        }
        if (rootReport.hasErrors()) {
            throw new ExportException("DCAT export aborted: invalid root configuration");
        }
    }

    private static ExportData buildExportData(ExportDataProvider provider) {
        return ExportData.builder().provider(provider).build();
    }

    private static void traceInputIfEnabled(ObjectMapper mapper, ExportData exportData, RootConfig root)
            throws ExportException {
        if (!root.trace()) {
            return;
        }
        try {
            String json = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(exportData);
            logger.info(json);
        } catch (JsonProcessingException e) {
            logger.warning(e.getMessage());
            // do not continue if trace can't be produced
            throw new ExportException("DCAT export aborted: trace output failed", e);
        }
    }

    private static MapBuildResult buildElementModels(RootConfig root, JaywayJsonFinder finder, Prefixes prefixes)
            throws IOException {

        Map<String, Model> models = new LinkedHashMap<>();
        Map<String, List<Resource>> subjects = new LinkedHashMap<>();
        Map<String, ResourceConfig> elementConfigs = new LinkedHashMap<>();

        for (Element element : root.elements()) {
            try (InputStream in = resolveElementFile(root.baseDir(), element.file())) {
                ResourceConfig resourceConfig = new ResourceConfigLoader().load(in);
                elementConfigs.put(element.id(), resourceConfig);

                ResourceMapper resourceMapper =
                        new ResourceMapper(resourceConfig, prefixes, element.typeCurieOrIri(), root.encodeInvalidIris());

                Model elementModel = resourceMapper.build(finder);

                // Collect all subjects by rdf:type (for later relation wiring)
                String typeIri = prefixes.expand(element.typeCurieOrIri());
                ResIterator it = elementModel.listResourcesWithProperty(RDF.type, elementModel.createResource(typeIri));

                List<Resource> subjectList = new ArrayList<>();
                while (it.hasNext()) {
                    subjectList.add(it.next());
                }

                models.put(element.id(), elementModel);
                if (!subjectList.isEmpty()) {
                    subjects.put(element.id(), subjectList);
                }
            }
        }

        return new MapBuildResult(models, subjects, elementConfigs);
    }

    private static void validateAllOrThrow(RootConfig root, Map<String, ResourceConfig> elementConfigs)
            throws ExportException {

        ValidationReport report = Validators.validateAll(root, elementConfigs);
        for (ValidationMessage message : report.messages()) {
            logger.log(message.severity() == Severity.ERROR ? Level.SEVERE : Level.WARNING, message.toString());
        }
        if (report.hasErrors()) {
            throw new ExportException("DCAT export aborted: validation errors in element configs");
        }
    }

    private static Model mergeModels(Prefixes prefixes, Map<String, Model> models) {
        Model model = ModelFactory.createDefaultModel();
        model.setNsPrefixes(prefixes.jena());
        models.values().forEach(model::add);
        return model;
    }

    private static void applyRelations(
            Model model, Prefixes prefixes, List<Relation> relations, Map<String, List<Resource>> subjects) {

        for (Relation relation : relations) {
            List<Resource> subjList = subjects.get(relation.subjectElementId());
            List<Resource> objList = subjects.get(relation.objectElementId());

            if (subjList == null || subjList.isEmpty() || objList == null || objList.isEmpty()) {
                continue;
            }

            Property property = model.createProperty(prefixes.expand(relation.predicateCurieOrIri()));

            // Deterministic iteration order for relation materialization
            subjList.sort(Dcat3ExporterBase::compareResources);
            objList.sort(Dcat3ExporterBase::compareResources);

            for (Resource s : subjList) {
                for (Resource o : objList) {
                    model.add(s, property, o);
                }
            }
        }
    }

    private static void writeAtomic(Model model, String writerName, OutputStream outputStream) throws IOException {
        // make writing atomic, make sure no half written output stream leaves this code.
        ByteArrayOutputStream buffer = new ByteArrayOutputStream(64 * 1024);
        model.write(buffer, writerName);
        buffer.writeTo(outputStream);
    }

    // ---------------------------------------------------------------------------
    // Small utilities
    // ---------------------------------------------------------------------------

    private static int compareResources(Resource a, Resource b) {
        String ka = a.isURIResource() ? a.getURI() : a.getId().getLabelString();
        String kb = b.isURIResource() ? b.getURI() : b.getId().getLabelString();
        return ka.compareTo(kb);
    }

    /**
     * Internal carrier for build results: element models, discovered subjects, and configs for
     * validation.
     */
    private record MapBuildResult(
            Map<String, Model> models,
            Map<String, List<Resource>> subjects,
            Map<String, ResourceConfig> elementConfigs) {}
}
