// SPDX-License-Identifier: (Apache-2.0 OR MIT)
// Generated by M365 Copilot on 2025-12-17
// Refactor: Split DCAT3 exporter into base + format-specific subclasses.
package io.gdcc.spi.export.dcat3;

import com.google.auto.service.AutoService;
import io.gdcc.spi.export.Exporter;
import java.util.Locale;

@AutoService( Exporter.class )
public class Dcat3ExporterJsonLd extends Dcat3ExporterBase {
    @Override
    public String getFormatName() {
        return "dcat3-jsonld";
    }

    @Override
    public String getDisplayName(Locale locale) {
        return "DCAT-3 (JSON-LD)";
    }

    @Override
    protected String getMediaTypeValue() {
        return "application/ld+json";
    }

    @Override
    protected String getJenaWriterName() {
        return "JSON-LD";
    }
}
